### ISSUE TITLE
Can't deploy on Vercel on the step by step instructions

### ISSUE THREAD

**Issue by fedeserbin** [mathix420/notion-charts#7] opened 2020-07-27 19:14 UTC
I get this error

![image](https://user-images.githubusercontent.com/58366373/88581463-94606700-d023-11ea-8d23-95ccf662c9fe.png)

I am putting Notion token

![image](https://user-images.githubusercontent.com/58366373/88581866-2d8f7d80-d024-11ea-9312-b324f7f2ced4.png)

Can you help me out? thanks!!!

**Comment by mathix420** [comment] 2020-07-27 19:48
Hi !

As I can see Vercel has again changed his interface. The variable `@token_v2` is a secret not an environment variable. If you know how to install the Vercel CLI you can add the `token_v2` variable https://vercel.com/docs/cli#commands/secrets

**Comment by mathix420** [comment] 2020-07-27 21:56
The issue is fixed by removing the use of `@token_v2` secrets c7d1165ceb18a6a99a3a1b34dc67dd1cd53eb10a.

I really think this is a bad thing that Vercel is no longer asking for missing secrets in the UI ...

(@fedeserbin just redeploy a new project on Vercel by clicking the Deploy button in [the readme](https://github.com/mathix420/notion-charts#usage))

**Closed by mathix420** 2020-07-27 21:56 UTC
